USE[INF2D_Alpha1_Shop];

Insert Into Preis(ArtikelID, Preis)values(1, 89.60);
Insert Into Preis(ArtikelID, Preis)values(13, 129);
Insert Into Preis(ArtikelID, Preis)values(25, 555);
Insert Into Preis(ArtikelID, Preis)values(37, 439);
Insert Into Preis(ArtikelID, Preis)values(49, 69);
Insert Into Preis(ArtikelID, Preis)values(61, 349);
Insert Into Preis(ArtikelID, Preis)values(73, 239);
Insert Into Preis(ArtikelID, Preis)values(85, 279);
Insert Into Preis(ArtikelID, Preis)values(97, 50);
Insert Into Preis(ArtikelID, Preis)values(109, 98);
Insert Into Preis(ArtikelID, Preis)values(121, 229);
Insert Into Preis(ArtikelID, Preis)values(133, 184);
Insert Into Preis(ArtikelID, Preis)values(145, 229);
Insert Into Preis(ArtikelID, Preis)values(157, 549);
Insert Into Preis(ArtikelID, Preis)values(169, 154);
Insert Into Preis(ArtikelID, Preis)values(181, 157);
Insert Into Preis(ArtikelID, Preis)values(193, 99);
Insert Into Preis(ArtikelID, Preis)values(205, 379);
Insert Into Preis(ArtikelID, Preis)values(265, 37);
Insert Into Preis(ArtikelID, Preis)values(277, 99);
