USE [INF2D_Alpha1_Shop];

INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Heimkino' ),'Optical Switch','Teilt ein Optical Audio-Signal auf');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Radio' ),'DAB Radio','Geniessen sie Radio neue in DAB+ Qualität');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = '3D' ),'Duplicator i3 Plus','Erlaubt es Ihnen ihre eigenen Modelle zu drucken');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Scanner' ),'ScnapSnap500i','Scannen sie neu mit glasklarer Aufklösung');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Game' ),'MarioKartDeluxe','Der Hit für die Nintendo Switch');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Spielkonsole' ),'Nintendo Switch','Die neuste Spielekonsole von Nintendo');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Spielkonsole' ),'Playstation4','Die aktuelle Spielekonsole von Sony');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Spielkonsole' ),'Microsoft XBox','Die aktuelle Spielekonsole von Microsoft');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Druckserver' ),'TPLink USB2.0D Printserver','Drucken in grossen Unternehmen organisieren');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Druckserver' ),'Silex USB Device Server','Eine Alternative zum Standard');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Modem' ),'Netgear Aircard Mobilfunk','Für alle die unterwegs nicht auf das Internet verzeichten wollen');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Modem' ),'Huawei E550 Mobilfunk','Unterwegs neu definiert');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Firewall' ),'Zyxel USG20W-VPN','Verbinden sie sich mit dem Netzwerk, auch wenn sie nicht physich in ihm sind');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Firewall' ),'Zyxel ZyWALL 110','Schützt ihre Netzwerk vor Angriffen');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Betriebssysteme' ),'Microsoft Windows 10 Pro (DE, 64-bit)','Der Klassiker für ihren Computer');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Betriebssysteme' ),'Microsoft Windows 7 Professional SP1 (DE, 64-bit)','Um Meilen besser als Windows 8.1 !!');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Büroanwendungen' ),'Banana Buchhaltung 8.0 2016 (DE, Windows)','Organisation im Büro');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Büroanwendungen' ),'Adobe Acrobat Standard DC (DE, Windows)','Haben sie Lust für etwas zu zahlen was auch gratis erhältlich ist?');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Sicherheit' ),'Kaspersky Internet Security 2017 ','Schützten sie ihren PC vor Malware und weiterem');
INSERT INTO Artikel (UnterkategorieID,Name,Beschreibung) values ((SELECT UnterkategorieID from Unterkategorie where Name = 'Sicherheit' ),'bitdefender Total Multi-device 2017 ESD ','Haben sie kein Antivirus Programm finden sie die Schädlinge');
