USE [INF2D_Alpha1_Shop];
CREATE TABLE Artikel
(
	ID BIGINT IDENTITY(1,12),
	Unterkategorie NVARCHAR(50) NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Beschreibung NVARCHAR(100) NOT NULL,
	CONSTRAINT pk_artikel PRIMARY KEY(ID),
	CONSTRAINT fk_artikel_gallerie FOREIGN KEY (ID) REFERENCES Gallerie(ID) ON UPDATE CASCADE
)